### ISSUE TITLE
issues following the tutorial

### ISSUE THREAD

**Issue by jpita** [crossbrowsertesting/selenium-webdriverio#5]
following the start from scratch tutorial I get

`Error: Couldn't find plugin "local" runner, neither as wdio scoped package "@wdio/local-runner" nor as community package "wdio-local-runner". Please make sure you have it installed!`

after installing the missing package I get 

`[0-0] 2020-06-04T09:09:22.388Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't find plugin "spec" reporter, neither as wdio scoped package "@wdio/spec-reporter" nor as community package "wdio-spec-reporter". Please make sure you have it installed!`

after installing the missing package I get

`[0-0] 2020-06-04T09:11:06.144Z ERROR webdriver: Request failed with status 404 due to Error: ERROR Unable to handle request - Invalid endpoint or request. (/session)`

**Comment by alexdefine** [comment]
Have you figured that out? Having exact same issue right now.

**Comment by jpita** [comment]
nop

**Comment by alexdefine** [comment]
Not sure if it will help, but when I specified the **path** in config error disappeared.
`hostname: 'hub.crossbrowsertesting.com',`
`port: 80,`
`path: '/wd/hub';`

**Comment by spsaxena** [comment]
After I upgraded my packages to 7.19.5 I encounter the same error only with yarn, npm does not complain

```
2022-05-17T02:20:03.166Z WARN @wdio/utils:shim: You are running tests with @wdio/sync which will be discontinued starting Node.js v16.Read more on https://github.com/webdriverio/webdriverio/discussions/6702
2022-05-17T02:20:03.796Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't find plugin "spec" reporter, neither as wdio scoped package "@wdio/spec-reporter" nor as community package "wdio-spec-reporter". Please make sure you have it installed!
    at initialisePlugin (U:\.yarn\cache\@wdio-utils-npm-7.19.5-de5464e1a3-74bff1a283.zip\node_modules\@wdio\utils\build\initialisePlugin.js:41:11)
    at BaseReporter.initReporter (U:\.yarn\cache\@wdio-runner-npm-7.19.5-0b1d40a79b-0847c6c714.zip\node_modules\@wdio\runner\build\reporter.js:154:58)
    at Array.map (<anonymous>)
    at new BaseReporter (U:\.yarn\cache\@wdio-runner-npm-7.19.5-0b1d40a79b-0847c6c714.zip\node_modules\@wdio\runner\build\reporter.js:22:50)
    at Runner.run (U:\.yarn\cache\@wdio-runner-npm-7.19.5-0b1d40a79b-0847c6c714.zip\node_modules\@wdio\runner\build\index.js:78:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
and I find the path is already specified to path: '/wd/hub'

how can I resolve/debug this further
